language: node_js
matrix:
  include:
  - node_js: stable
  - node_js: v6
    env: BACKCOMPAT=true
script:
  - set -e
  - npm run build
  - npm run coverage
  # - if [ "x$BACKCOMPAT" = "x" ]; then npm run test; fi
  # - rm -rf src
  # - mv dist src
  # - if [ $BACKCOMPAT = "true" ]; then npm run built-tests; else npm run test; fi
cache:
  - node_modules
after_success:
  - bash <(curl -s https://codecov.io/bash)
